url: "" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "" # the subpath of your site, e.g. /blog
title: "Jovial Badger" # the name of your site, e.g. ACME Corp.
baseurl: "/beta_jb" 
default_site_url: "jovialbadger.co.uk"
